//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olimpia.Balanceador.Infraestructura.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Climates2
    {
        public int ClimaID { get; set; }
        public string Description { get; set; }
        public int Temperature { get; set; }
        public int Humidity { get; set; }
        public int Wind { get; set; }
        public string City { get; set; }
        public System.DateTime Date { get; set; }
    }
}
